---
# ============================================================
# requirements.yml – Dépendances du repo playbook
# ============================================================
# Installation :
#   ansible-galaxy role install -r requirements.yml
#   ansible-galaxy collection install -r requirements.yml
# ============================================================

roles:
  - name: wordpress_ops
    src: https://github.com/votre-org/ansible-role-wordpress-ops.git
    scm: git
    version: main   # ou un tag : v1.0.0

collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: amazon.aws
    version: ">=7.0.0"
