---
# ============================================================
# requirements.yml – Dépendances du repo playbook
# ============================================================
# Installation :
#   ansible-galaxy role install -r roles/requirements.yml
#   ansible-galaxy collection install -r requirements.yml
# ============================================================

collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: amazon.aws
    version: ">=7.0.0"
